let constants = {};

constants.TAGS_DOCUMENT_ID = 'TAGS_DOCUMENT_ID';
constants.TAG_ROOT_ID = 'EVERYTHING';
constants.TAG_ACCESSIBILITY_ID = 'ACCESSIBILITY';
constants.TAG_META_ID = 'META';
constants.TAG_DE_ID = 'LANG_DE';
constants.TAG_AUT_ID = 'AUT';
constants.TAG_TYPE_LINK_ID = 'TYPE_LINK';

constants.TAG_COUNTRY_ID = 'COUNTRY';
constants.TAG_LANGUAGE_ID = 'LANGUAGE';
constants.TAG_ENTRY_TYPE_ID = 'ENTRY_TYPE';
constants.TAG_TARGETGROUP_ID = 'TYPE_DISABILITY';
constants.TAGS_MANDATORY = [constants.TAG_ACCESSIBILITY_ID, constants.TAG_COUNTRY_ID, constants.TAG_LANGUAGE_ID, constants.TAG_ENTRY_TYPE_ID, constants.TAG_TARGETGROUP_ID];

constants.EVENT_DB_CONNECTION_LOST = 'EVENT_DB_CONNECTION_LOST';
constants.EVENT_DB_PULL_UPDATED = 'EVENT_DB_PULL_UPDATED';
constants.EVENT_DB_UNAUTHORIZED = 'EVENT_DB_UNAUTHORIZED';
constants.EVENT_DB_SYNC_STATE_CHANGE = 'EVENT_DB_SYNC_STATE_CHANGE';
constants.EVENT_DB_INITIALIZED = 'EVENT_DB_INITIALIZED';
constants.EVENT_DB_CLOSED = 'EVENT_DB_CLOSED';
constants.EVENT_DB_DATAMODEL_UPDATE = 'EVENT_DB_DATAMODEL_UPDATE';

export {constants};